package DS_Projektas;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
* Klasė sąsajos atliekamiems veiksmams realizuoti
*/
public class Sasaja extends javax.swing.JFrame {

    public Sasaja() {
        initComponents();
    }
    // Pagrindinis duomenų list
        UnrolledLinkedList<Filmas> filmuList = new UnrolledLinkedList<Filmas>(8);
        File f1;
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Veiksmai su duomenimis:");
        jLabel2.setToolTipText("");

        jButton1.setText("Skaityti ir spausdinti duomenis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Ar yra tokių metų filmas?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pridėti naują filmą");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Naikinti pasirinkto nr. filmą");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Rikiuoti duomenis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Atliks duomenų nuskaitymą ir spausdinimą
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      	JFileChooser fc = new JFileChooser(".");
		int rez = fc.showOpenDialog(Sasaja.this);
               
		if (rez == JFileChooser.APPROVE_OPTION) {
			f1 = fc.getSelectedFile();
			filmuList = FilmuAtranka.loadAndPrint(f1, jTextArea1);
                       FilmuAtranka.PrintList(filmuList, jTextArea1);
			if (!filmuList.isEmpty()) {
				JOptionPane.showMessageDialog(null, "Duomenų skaitymas sėkmingas",
					"Skaitymas - rašymas", JOptionPane.INFORMATION_MESSAGE);
			}
		} else if (rez == JFileChooser.CANCEL_OPTION) {
			JOptionPane.showMessageDialog(Sasaja.this,
					"Skaitymo atsisakyta (paspaustas ESC arba Cancel)",
					"Skaitymas - rašymas", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Atliks objekto paiešką ir grąžins atitinkamai ar yra toks objektas liste ar ne
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UnrolledLinkedList<Filmas> tinkami = new UnrolledLinkedList<Filmas>();
        int metai = Integer.parseInt(jTextField1.getText());
        if(metai != 0 )
        jTextArea1.append("Įvesti metai: " + metai + "\n");
        else
            jTextArea1.append("Įvesti nekorektiški metai:" + metai + "\n");
        for(int i =0; i<filmuList.size(); i++)
        if(filmuList.contains(filmuList.get(i)) && filmuList.get(i).getMetai()== metai)
        { 
            tinkami.add(filmuList.get(i));
        } 
       if(!tinkami.isEmpty())
        FilmuAtranka.PrintList(tinkami, jTextArea1);
       else
          jTextArea1.append("Nėra tokių metų filmų\n");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Atliks naujo objekto pridėjimą į listą
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String line = jTextField3.getText();
                        filmuList.add(new Filmas(line));
			if (!filmuList.isEmpty()) {
				FilmuAtranka.PrintList(filmuList, jTextArea1);
		
                        }      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Atliks pasirinkto numerio objekto šalinimą iš listo
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int numeris = Integer.parseInt(jTextField2.getText());
        if(numeris != 0 )
        jTextArea1.append("\nPašalintas filmas: " + filmuList.get(numeris-1) + "\n");
        else
            jTextArea1.append("""
                              \u012evestas nekorekti\u0161kas numeris :
                              """);
        if(numeris<= filmuList.size())
        {   Filmas pasalintas = filmuList.get(numeris-1);
            filmuList.remove(filmuList.get(numeris-1));
        }
        else
            jTextArea1.append("Tokio numerio nėra\n");
            FilmuAtranka.PrintList(filmuList, jTextArea1);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Atliks listo rikaivimą pagal pelną didėjimo tvarka
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        filmuList.sortJava(Filmas.pagalPelną);
        if (!filmuList.isEmpty()) 
        {
            FilmuAtranka.PrintList(filmuList, jTextArea1);
        }
        else
            jTextArea1.append("Rikaivimas nepavyko\n");
    }//GEN-LAST:event_jButton5ActionPerformed
                                                                                                                                                                                                                                                                                                                                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sasaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables


}
